import type {
  CampaignLead,
  OutreachQueueItem,
  ProspectDetails,
  SuppressionRecord,
  WhatsAppConversation,
  WhatsAppMessage,
  WhatsAppTemplate,
} from "./types";

const hoursAgo = (h: number) =>
  new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
const minsAgo = (m: number) =>
  new Date(Date.now() - m * 60 * 1000).toISOString();
const hoursFromNow = (h: number) =>
  new Date(Date.now() + h * 60 * 60 * 1000).toISOString();

export const mockConversations: WhatsAppConversation[] = [
  {
    id: "c1",
    prospect_id: "p1",
    business_name: "Cape Plumbing Co",
    contact_name: "James",
    phone_number: "+27 82 000 0001",
    source: "Meta Ad",
    crm_stage: "Interested",
    lead_score: 78,
    assigned_to: "Alex",
    last_message: "What does the report include?",
    last_message_at: minsAgo(12),
    unread_count: 1,
    last_inbound_at: minsAgo(12),
    service_window_expires_at: hoursFromNow(23),
    service_window_status: "open",
    opt_out: false,
    suppressed: false,
    tags: ["plumbing", "atlantic-seaboard"],
    niche: "Plumbing",
    location: "Atlantic Seaboard",
    first_contact_at: hoursAgo(26),
  },
  {
    id: "c2",
    prospect_id: "p2",
    business_name: "Sparks Electrical",
    contact_name: "Thandi",
    phone_number: "+27 83 220 1144",
    source: "Outbound",
    crm_stage: "Replied",
    lead_score: 62,
    assigned_to: "Alex",
    last_message: "Send it through, thanks.",
    last_message_at: minsAgo(48),
    unread_count: 0,
    last_inbound_at: minsAgo(48),
    service_window_expires_at: hoursFromNow(22),
    service_window_status: "open",
    opt_out: false,
    suppressed: false,
    tags: ["electrical"],
    niche: "Electrical contractors",
    location: "Northern Suburbs",
  },
  {
    id: "c3",
    prospect_id: "p3",
    business_name: "GreenLeaf Landscaping",
    contact_name: "Pieter",
    phone_number: "+27 71 555 0190",
    source: "Outbound",
    crm_stage: "Contacted",
    lead_score: 41,
    assigned_to: "VA",
    last_message: "Template: mjr_followup_v1",
    last_message_at: hoursAgo(30),
    unread_count: 0,
    last_inbound_at: null,
    service_window_expires_at: null,
    service_window_status: "closed",
    opt_out: false,
    suppressed: false,
    tags: ["landscaping"],
    niche: "Landscaping",
    location: "Durbanville",
  },
  {
    id: "c4",
    prospect_id: "p4",
    business_name: "BlueWave Pools",
    contact_name: "Megan",
    phone_number: "+27 82 998 7321",
    source: "Meta Ad",
    crm_stage: "Call Booked",
    lead_score: 91,
    assigned_to: "Alex",
    last_message: "Booked Tuesday 10am 👍",
    last_message_at: hoursAgo(3),
    unread_count: 0,
    last_inbound_at: hoursAgo(3),
    service_window_expires_at: hoursFromNow(21),
    service_window_status: "open",
    opt_out: false,
    suppressed: false,
    tags: ["pool", "hot"],
    niche: "Pool services",
    location: "Camps Bay",
  },
  {
    id: "c5",
    prospect_id: "p5",
    business_name: "Aircool HVAC",
    contact_name: "Sipho",
    phone_number: "+27 84 110 2200",
    source: "Outbound",
    crm_stage: "Qualified",
    lead_score: 70,
    assigned_to: "Alex",
    last_message: "Yes, would like the report.",
    last_message_at: hoursAgo(20),
    unread_count: 2,
    last_inbound_at: hoursAgo(20),
    service_window_expires_at: hoursFromNow(4),
    service_window_status: "closing_soon",
    opt_out: false,
    suppressed: false,
    tags: ["hvac"],
    niche: "HVAC",
    location: "Southern Suburbs",
  },
  {
    id: "c6",
    prospect_id: "p6",
    business_name: "Pristine Cleaning",
    contact_name: "Linda",
    phone_number: "+27 76 333 0098",
    source: "Outbound",
    crm_stage: "Not Interested",
    lead_score: 18,
    assigned_to: "VA",
    last_message: "Not for us, thanks.",
    last_message_at: hoursAgo(50),
    unread_count: 0,
    last_inbound_at: hoursAgo(50),
    service_window_expires_at: null,
    service_window_status: "closed",
    opt_out: false,
    suppressed: false,
    tags: ["cleaning"],
    niche: "Residential cleaning",
    location: "Sea Point",
  },
  {
    id: "c7",
    prospect_id: "p7",
    business_name: "PestStop SA",
    contact_name: "Unknown",
    phone_number: "+27 79 200 3344",
    source: "Outbound",
    crm_stage: "Do Not Contact",
    lead_score: 0,
    assigned_to: "VA",
    last_message: "Stop messaging me.",
    last_message_at: hoursAgo(72),
    unread_count: 0,
    last_inbound_at: hoursAgo(72),
    service_window_expires_at: null,
    service_window_status: "closed",
    opt_out: true,
    suppressed: true,
    tags: ["suppressed"],
    niche: "Pest control",
    location: "Claremont",
  },
  {
    id: "c8",
    prospect_id: "p8",
    business_name: "Foundation Builders",
    contact_name: "Ryan",
    phone_number: "+27 82 776 4410",
    source: "Meta Ad",
    crm_stage: "Report Sent",
    lead_score: 84,
    assigned_to: "Alex",
    last_message: "Looking it over now.",
    last_message_at: minsAgo(180),
    unread_count: 0,
    last_inbound_at: minsAgo(180),
    service_window_expires_at: hoursFromNow(20),
    service_window_status: "open",
    opt_out: false,
    suppressed: false,
    tags: ["building"],
    niche: "Building/renovation",
    location: "Cape Town",
  },
];

export const mockMessages: Record<string, WhatsAppMessage[]> = {
  c1: [
    {
      id: "m1",
      conversation_id: "c1",
      direction: "system",
      message_type: "system",
      body: "Started from Click-to-WhatsApp ad",
      status: "received",
      created_at: hoursAgo(26),
    },
    {
      id: "m2",
      conversation_id: "c1",
      direction: "inbound",
      message_type: "text",
      body: "Hi, saw your ad. What's the missed jobs report?",
      status: "received",
      created_at: hoursAgo(26),
      sender_name: "James",
    },
    {
      id: "m3",
      conversation_id: "c1",
      direction: "outbound",
      message_type: "text",
      body: "Hi James — thanks for reaching out. It's a short report showing where Cape Plumbing Co may be losing local enquiries online. Want me to send the short version?",
      status: "read",
      created_at: hoursAgo(25),
      sender_name: "Alex",
    },
    {
      id: "m4",
      conversation_id: "c1",
      direction: "inbound",
      message_type: "text",
      body: "What does the report include?",
      status: "received",
      created_at: minsAgo(12),
      sender_name: "James",
    },
  ],
  c2: [
    {
      id: "m5",
      conversation_id: "c2",
      direction: "outbound",
      message_type: "template",
      body: "Hi Thandi, this is Alex from Attract Acquisition. I noticed your Google listing has no recent photos for Sparks Electrical. I made a short Missed Jobs Report showing where you may be losing local enquiries. Would you like me to send it?",
      template_name: "mjr_intro_short_v1",
      template_params: {
        "1": "Thandi",
        "2": "your Google listing has no recent photos",
        "3": "Sparks Electrical",
      },
      status: "delivered",
      created_at: hoursAgo(2),
      sender_name: "Alex",
    },
    {
      id: "m6",
      conversation_id: "c2",
      direction: "inbound",
      message_type: "text",
      body: "Send it through, thanks.",
      status: "received",
      created_at: minsAgo(48),
      sender_name: "Thandi",
    },
    {
      id: "m7",
      conversation_id: "c2",
      direction: "system",
      message_type: "system",
      body: "24h window opened",
      status: "received",
      created_at: minsAgo(48),
    },
  ],
  c3: [
    {
      id: "m8",
      conversation_id: "c3",
      direction: "outbound",
      message_type: "template",
      body: "Hi Pieter, just following up on the Missed Jobs Report for GreenLeaf Landscaping...",
      template_name: "mjr_followup_v1",
      status: "delivered",
      created_at: hoursAgo(30),
      sender_name: "VA",
    },
  ],
  c4: [
    {
      id: "m9",
      conversation_id: "c4",
      direction: "inbound",
      message_type: "text",
      body: "Saw your ad — keen to chat.",
      status: "received",
      created_at: hoursAgo(8),
      sender_name: "Megan",
    },
    {
      id: "m10",
      conversation_id: "c4",
      direction: "outbound",
      message_type: "text",
      body: "Hi Megan — happy to. Want to grab a quick call this week?",
      status: "read",
      created_at: hoursAgo(7),
      sender_name: "Alex",
    },
    {
      id: "m11",
      conversation_id: "c4",
      direction: "inbound",
      message_type: "text",
      body: "Booked Tuesday 10am 👍",
      status: "received",
      created_at: hoursAgo(3),
      sender_name: "Megan",
    },
    {
      id: "m12",
      conversation_id: "c4",
      direction: "system",
      message_type: "system",
      body: "Call booked",
      status: "received",
      created_at: hoursAgo(3),
    },
  ],
  c5: [
    {
      id: "m13",
      conversation_id: "c5",
      direction: "outbound",
      message_type: "template",
      body: "Hi Sipho, this is Alex from Attract Acquisition...",
      template_name: "mjr_intro_short_v1",
      status: "delivered",
      created_at: hoursAgo(22),
      sender_name: "Alex",
    },
    {
      id: "m14",
      conversation_id: "c5",
      direction: "inbound",
      message_type: "text",
      body: "Yes, would like the report.",
      status: "received",
      created_at: hoursAgo(20),
      sender_name: "Sipho",
    },
  ],
  c6: [
    {
      id: "m15",
      conversation_id: "c6",
      direction: "outbound",
      message_type: "template",
      body: "Hi Linda...",
      template_name: "mjr_intro_short_v1",
      status: "delivered",
      created_at: hoursAgo(52),
      sender_name: "VA",
    },
    {
      id: "m16",
      conversation_id: "c6",
      direction: "inbound",
      message_type: "text",
      body: "Not for us, thanks.",
      status: "received",
      created_at: hoursAgo(50),
      sender_name: "Linda",
    },
  ],
  c7: [
    {
      id: "m17",
      conversation_id: "c7",
      direction: "outbound",
      message_type: "template",
      body: "Hi...",
      template_name: "mjr_intro_short_v1",
      status: "delivered",
      created_at: hoursAgo(74),
      sender_name: "VA",
    },
    {
      id: "m18",
      conversation_id: "c7",
      direction: "inbound",
      message_type: "text",
      body: "Stop messaging me.",
      status: "received",
      created_at: hoursAgo(72),
    },
    {
      id: "m19",
      conversation_id: "c7",
      direction: "system",
      message_type: "system",
      body: "Suppression applied",
      status: "received",
      created_at: hoursAgo(72),
    },
  ],
  c8: [
    {
      id: "m20",
      conversation_id: "c8",
      direction: "inbound",
      message_type: "text",
      body: "Looking it over now.",
      status: "received",
      created_at: minsAgo(180),
      sender_name: "Ryan",
    },
  ],
};

export const mockTemplates: WhatsAppTemplate[] = [
  {
    id: "t1",
    template_name: "mjr_intro_short_v1",
    category: "Marketing",
    language: "en",
    status: "Approved",
    body: "Hi {{1}}, this is Alex from Attract Acquisition.\nI noticed {{2}} for {{3}}.\nI made a short Missed Jobs Report showing where you may be losing local enquiries.\nWould you like me to send it?",
    variables: ["contact_name", "observation", "business_name"],
    use_case: "First touch outbound to scraped prospect.",
    last_used_at: hoursAgo(2),
    sent_count: 184,
    reply_rate: 0.21,
    opt_out_rate: 0.012,
  },
  {
    id: "t2",
    template_name: "mjr_followup_v1",
    category: "Marketing",
    language: "en",
    status: "Approved",
    body: "Hi {{1}}, just following up on the Missed Jobs Report for {{2}}.\nIt highlights {{3}} and a few simple fixes that could help generate more local enquiries.\nShould I send it through?",
    variables: ["contact_name", "business_name", "observation"],
    use_case: "Follow-up if no reply within 48h.",
    last_used_at: hoursAgo(30),
    sent_count: 92,
    reply_rate: 0.16,
    opt_out_rate: 0.018,
  },
  {
    id: "t3",
    template_name: "mjr_delivery_v1",
    category: "Marketing",
    language: "en",
    status: "Approved",
    body: "Hi {{1}}, here is the Missed Jobs Report for {{2}}.\nIt covers:\n1. What may be costing you enquiries\n2. Where your online presence can improve\n3. The next steps I would recommend\nYou can view it here: {{3}}",
    variables: ["contact_name", "business_name", "report_url"],
    use_case: "Deliver the actual report.",
    last_used_at: hoursAgo(12),
    sent_count: 47,
    reply_rate: 0.34,
    opt_out_rate: 0.004,
  },
  {
    id: "t4",
    template_name: "mjr_report_followup_v1",
    category: "Marketing",
    language: "en",
    status: "Approved",
    body: "Hi {{1}}, did you get a chance to look at the Missed Jobs Report for {{2}}?\nThe main opportunity I saw was {{3}}.\nWould you like me to explain how we would fix that?",
    variables: ["contact_name", "business_name", "main_opportunity"],
    use_case: "Re-open conversation 24-48h after report sent.",
    last_used_at: hoursAgo(40),
    sent_count: 38,
    reply_rate: 0.26,
    opt_out_rate: 0.01,
  },
  {
    id: "t5",
    template_name: "book_call_prompt_v1",
    category: "Marketing",
    language: "en",
    status: "Approved",
    body: "Hi {{1}}, based on the Missed Jobs Report for {{2}}, there are a few clear opportunities to improve enquiry flow.\nWould you like to book a short call to go through the findings?",
    variables: ["contact_name", "business_name"],
    use_case: "Push toward discovery call.",
    last_used_at: hoursAgo(60),
    sent_count: 24,
    reply_rate: 0.4,
    opt_out_rate: 0.0,
  },
  {
    id: "t6",
    template_name: "proof_sprint_intro_v1",
    category: "Marketing",
    language: "en",
    status: "Approved",
    body: "Hi {{1}}, based on what we found for {{2}}, the next step would be a Proof Sprint.\nIt is a short project where we improve your online proof, enquiry flow, and local conversion points before discussing any longer-term work.\nWould you like the details?",
    variables: ["contact_name", "business_name"],
    use_case: "Introduce paid Proof Sprint offer.",
    last_used_at: hoursAgo(90),
    sent_count: 12,
    reply_rate: 0.5,
    opt_out_rate: 0.0,
  },
  {
    id: "t7",
    template_name: "close_loop_v1",
    category: "Marketing",
    language: "en",
    status: "Approved",
    body: "Hi {{1}}, closing the loop on this.\nShould I leave the Missed Jobs Report for {{2}}, or is improving enquiry flow not a priority right now?",
    variables: ["contact_name", "business_name"],
    use_case: "Final follow-up before closing as lost.",
    last_used_at: hoursAgo(120),
    sent_count: 31,
    reply_rate: 0.19,
    opt_out_rate: 0.025,
  },
  {
    id: "t8",
    template_name: "opt_out_confirm_v1",
    category: "Utility",
    language: "en",
    status: "Approved",
    body: "Thanks {{1}}, I have noted that you do not want to receive further messages from Attract Acquisition.\nYou will not be contacted again about this.",
    variables: ["contact_name"],
    use_case: "Confirm opt-out request received.",
    last_used_at: hoursAgo(72),
    sent_count: 9,
    reply_rate: 0.0,
    opt_out_rate: 0.0,
  },
];

export const mockOutreachQueue: OutreachQueueItem[] = [
  {
    id: "q1",
    prospect_id: "px1",
    business_name: "Atlantic Roof Care",
    contact_name: "Brett",
    phone_number: "+27 82 411 9920",
    niche: "Roofing",
    location: "Sea Point",
    template_name: "mjr_intro_short_v1",
    template_params: {
      "1": "Brett",
      "2": "your last Instagram post is from 2023",
      "3": "Atlantic Roof Care",
    },
    draft_preview:
      "Hi Brett, this is Alex from Attract Acquisition. I noticed your last Instagram post is from 2023 for Atlantic Roof Care. I made a short Missed Jobs Report showing where you may be losing local enquiries. Would you like me to send it?",
    ai_observation: "Instagram inactive since 2023; Google listing missing photos.",
    risk_score: 12,
    compliance_status: "ok",
    status: "Pending Approval",
    created_at: minsAgo(20),
    created_by: "Claude",
  },
  {
    id: "q2",
    prospect_id: "px2",
    business_name: "Boland Electrical",
    contact_name: "Hannes",
    phone_number: "+27 83 776 0011",
    niche: "Electrical contractors",
    location: "Durbanville",
    template_name: "mjr_intro_short_v1",
    template_params: {
      "1": "Hannes",
      "2": "your Google reviews dropped to 3.6",
      "3": "Boland Electrical",
    },
    draft_preview:
      "Hi Hannes, this is Alex from Attract Acquisition. I noticed your Google reviews dropped to 3.6 for Boland Electrical. I made a short Missed Jobs Report showing where you may be losing local enquiries. Would you like me to send it?",
    ai_observation: "Google rating fell from 4.5 to 3.6 in last 90 days.",
    risk_score: 18,
    compliance_status: "ok",
    status: "Pending Approval",
    created_at: minsAgo(45),
    created_by: "Claude",
  },
  {
    id: "q3",
    prospect_id: "px3",
    business_name: "Tableview Pest Pros",
    contact_name: "Sandra",
    phone_number: "+27 71 092 8821",
    niche: "Pest control",
    location: "Tableview",
    template_name: "mjr_intro_short_v1",
    template_params: {
      "1": "Sandra",
      "2": "your website quote form is broken",
      "3": "Tableview Pest Pros",
    },
    draft_preview:
      "Hi Sandra, this is Alex from Attract Acquisition. I noticed your website quote form is broken for Tableview Pest Pros...",
    ai_observation: "Quote form returns 500 error on submit.",
    risk_score: 8,
    compliance_status: "ok",
    status: "Approved",
    created_at: hoursAgo(2),
    created_by: "Claude",
    approved_by: "Alex",
    approved_at: minsAgo(30),
  },
  {
    id: "q4",
    prospect_id: "px4",
    business_name: "SunCoast Pools",
    contact_name: "Marius",
    phone_number: "+27 84 332 8800",
    niche: "Pool services",
    location: "Hout Bay",
    template_name: "mjr_followup_v1",
    template_params: {
      "1": "Marius",
      "2": "SunCoast Pools",
      "3": "weak local trust signals",
    },
    draft_preview:
      "Hi Marius, just following up on the Missed Jobs Report for SunCoast Pools. It highlights weak local trust signals and a few simple fixes...",
    ai_observation: "No reply to first touch 48h ago.",
    risk_score: 15,
    compliance_status: "ok",
    status: "Draft",
    created_at: minsAgo(5),
    created_by: "VA",
  },
  {
    id: "q5",
    prospect_id: "px5",
    business_name: "Ezi-Garden Landscaping",
    contact_name: "Jaco",
    phone_number: "+27 79 200 3344",
    niche: "Landscaping",
    location: "Claremont",
    template_name: "mjr_intro_short_v1",
    template_params: {
      "1": "Jaco",
      "2": "no recent project photos",
      "3": "Ezi-Garden Landscaping",
    },
    draft_preview:
      "Hi Jaco, this is Alex from Attract Acquisition. I noticed no recent project photos for Ezi-Garden Landscaping...",
    ai_observation: "Phone matches a suppressed record.",
    risk_score: 95,
    compliance_status: "blocked",
    status: "Pending Approval",
    created_at: minsAgo(15),
    created_by: "Claude",
  },
  {
    id: "q6",
    prospect_id: "px6",
    business_name: "Coastal HVAC",
    contact_name: "Naledi",
    phone_number: "+27 82 555 0190",
    niche: "HVAC",
    location: "Bloubergstrand",
    template_name: "mjr_intro_short_v1",
    template_params: {
      "1": "Naledi",
      "2": "your Google listing has no service area set",
      "3": "Coastal HVAC",
    },
    draft_preview:
      "Hi Naledi, this is Alex from Attract Acquisition. I noticed your Google listing has no service area set for Coastal HVAC...",
    ai_observation: "GMB service area blank; missing service categories.",
    risk_score: 10,
    compliance_status: "ok",
    status: "Sent",
    created_at: hoursAgo(6),
    created_by: "Claude",
    approved_by: "Alex",
    approved_at: hoursAgo(5),
    sent_at: hoursAgo(5),
  },
];

export const mockSuppressionList: SuppressionRecord[] = [
  {
    id: "s1",
    phone_number: "+27 79 200 3344",
    business_name: "PestStop SA",
    reason: "Opted out",
    source: "Inbound STOP",
    created_at: hoursAgo(72),
    created_by: "System",
    notes: "Replied 'stop messaging me' on outbound template.",
  },
  {
    id: "s2",
    phone_number: "+27 82 100 9988",
    business_name: "QuickFix Plumbing",
    reason: "Wrong number",
    source: "Manual",
    created_at: hoursAgo(120),
    created_by: "Alex",
  },
  {
    id: "s3",
    phone_number: "+27 71 003 2200",
    business_name: "Unknown",
    reason: "Complaint",
    source: "Manual",
    created_at: hoursAgo(200),
    created_by: "Alex",
    notes: "Called and complained about messaging.",
  },
  {
    id: "s4",
    phone_number: "+27 84 882 1100",
    business_name: "OldCo Electrical",
    reason: "Duplicate",
    source: "System",
    created_at: hoursAgo(300),
    created_by: "System",
  },
];

export const mockCampaignLeads: CampaignLead[] = [
  {
    id: "cl1",
    conversation_id: "c1",
    phone_number: "+27 82 000 0001",
    business_name: "Cape Plumbing Co",
    contact_name: "James",
    campaign_name: "MJR-Plumbers-WC-Q2",
    adset_name: "Plumbers · Atlantic Seaboard",
    ad_name: "Missed Jobs Report — short v3",
    initial_message: "Hi, saw your ad. What's the missed jobs report?",
    received_at: hoursAgo(26),
    lead_status: "Qualified",
    service_window_expires_at: hoursFromNow(23),
    assigned_to: "Alex",
    niche: "Plumbing",
    location: "Atlantic Seaboard",
  },
  {
    id: "cl2",
    conversation_id: "c4",
    phone_number: "+27 82 998 7321",
    business_name: "BlueWave Pools",
    contact_name: "Megan",
    campaign_name: "MJR-Pools-WC-Q2",
    adset_name: "Pool services · Atlantic Seaboard",
    ad_name: "Discovery call CTA",
    initial_message: "Saw your ad — keen to chat.",
    received_at: hoursAgo(8),
    lead_status: "Booked",
    service_window_expires_at: hoursFromNow(21),
    assigned_to: "Alex",
    niche: "Pool services",
    location: "Camps Bay",
  },
  {
    id: "cl3",
    conversation_id: "c8",
    phone_number: "+27 82 776 4410",
    business_name: "Foundation Builders",
    contact_name: "Ryan",
    campaign_name: "MJR-Builders-WC-Q2",
    adset_name: "Building · Cape Town",
    ad_name: "Missed Jobs Report — long v1",
    initial_message: "Interested in the report.",
    received_at: minsAgo(180),
    lead_status: "Assigned",
    service_window_expires_at: hoursFromNow(20),
    assigned_to: "Alex",
    niche: "Building/renovation",
    location: "Cape Town",
  },
  {
    id: "cl4",
    conversation_id: "n1",
    phone_number: "+27 83 882 0011",
    business_name: "Unknown",
    contact_name: "Unknown",
    campaign_name: "MJR-Cleaners-WC-Q2",
    adset_name: "Cleaning · Southern Suburbs",
    ad_name: "Local enquiries CTA",
    initial_message: "Hi 👋",
    received_at: minsAgo(15),
    lead_status: "New",
    service_window_expires_at: hoursFromNow(23.5),
    niche: "Residential cleaning",
    location: "Southern Suburbs",
  },
  {
    id: "cl5",
    conversation_id: "n2",
    phone_number: "+27 71 776 2299",
    business_name: "Unknown",
    contact_name: "Unknown",
    campaign_name: "MJR-HVAC-WC-Q2",
    adset_name: "HVAC · Northern Suburbs",
    ad_name: "Lead form CTA",
    initial_message: "Tell me more please",
    received_at: minsAgo(40),
    lead_status: "New",
    service_window_expires_at: hoursFromNow(23),
    niche: "HVAC",
    location: "Northern Suburbs",
  },
];

export const mockProspects: Record<string, ProspectDetails> = {
  p1: {
    id: "p1",
    business_name: "Cape Plumbing Co",
    contact_name: "James",
    phone_number: "+27 82 000 0001",
    location: "Atlantic Seaboard",
    niche: "Plumbing",
    source: "Meta Ad",
    assigned_owner: "Alex",
    first_contact_at: hoursAgo(26),
    last_inbound_at: minsAgo(12),
    qualification: {
      google_listing: "claimed",
      instagram_active: false,
      meta_ads_running: false,
      website_quality: "average",
      reviews_count: 38,
      reviews_rating: 4.2,
      main_gap: "Quote form is buried below the fold; weak local proof.",
      suggested_angle: "Lead with quote-flow fix + local trust signals.",
    },
    compliance: {
      opt_out: false,
      suppressed: false,
      consent_note: "Inbound from Meta Click-to-WhatsApp ad.",
    },
    internal_notes: "James is the owner. Mentioned competitor undercut him last week.",
  },
};

export const defaultProspect = (
  conv: WhatsAppConversation,
): ProspectDetails => ({
  id: conv.prospect_id,
  business_name: conv.business_name,
  contact_name: conv.contact_name,
  phone_number: conv.phone_number,
  location: conv.location ?? "Cape Town",
  niche: conv.niche ?? "Local services",
  source: conv.source,
  assigned_owner: conv.assigned_to,
  first_contact_at: conv.first_contact_at ?? conv.last_message_at,
  last_inbound_at: conv.last_inbound_at,
  qualification: {
    google_listing: "claimed",
    instagram_active: true,
    meta_ads_running: false,
    website_quality: "average",
    reviews_count: 24,
    reviews_rating: 4.1,
    main_gap: "Weak online proof and unclear quote flow.",
    suggested_angle: "Lead with Missed Jobs Report and local proof fix.",
  },
  compliance: {
    opt_out: conv.opt_out,
    suppressed: conv.suppressed,
    consent_note:
      conv.source === "Meta Ad"
        ? "Inbound from Meta Click-to-WhatsApp ad."
        : "Outbound permission-based outreach.",
  },
  internal_notes: "",
});
